[package]
name = "hutils"
version = "0.1.1"
authors = ["hansung <hansung080@hanmail.net>"]
description = "various utilities"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hansung080/hutils"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3